# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  release:
      types:
        - created
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 kafkabroker" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 schemaregistry" | sudo tee -a /etc/hosts
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set Release version env variable
      run: | 
            echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/kafka-connect-transform-tojsonstring/kafka-connect-transform-tojsonstring/target/components/packages/an0r0c-kafka-connect-transform-record2jsonstring-${{ env.RELEASE_VERSION }}.zip
        asset_name: an0r0c-kafka-connect-transform-record2jsonstring-${{ github.ref }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
